version: '3.0'

services: 
  posgresql_db:
    image: postgres:12-alpine
    container_name: spring_homework_db
    ports: 
      - '10001:5432'
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: metanet_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metanet

  pgadmin:
    image: dpage/pgadmin4:4
    container_name: spring_homework_pgadmin
    ports: 
      - '10000:80'
    environment: 
     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
     PGADMIN_DEFAULT_PASSWORD: password
